#!/bin/bash
# Script to help create Widget Extension in Xcode

echo "📱 Widget Extension Setup Guide"
echo "================================"
echo ""
echo "Home Screen widgets MUST be in a Widget Extension target."
echo ""
echo "To create the extension:"
echo ""
echo "1. Open Xcode:"
echo "   open Triply.xcodeproj"
echo ""
echo "2. File → New → Target"
echo "3. Select 'Widget Extension'"
echo "4. Name: TriplyWidgetExtension"
echo "5. Check 'Include Configuration Intent'"
echo "6. Click Finish"
echo ""
echo "7. Move widget files to extension:"
echo "   - Drag Widgets/*.swift to TriplyWidgetExtension folder"
echo "   - Update target membership (check extension, uncheck main app)"
echo ""
echo "8. Update extension's main file with @main WidgetBundle"
echo ""
echo "9. Build extension scheme"
echo "10. Widgets will appear in widget gallery!"
echo ""
