name: Triply
options:
  bundleIdPrefix: com.triply
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

targets:
  Triply:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: .
        excludes:
          - "*.md"
          - ".gitignore"
          - "project.yml"
          - "create_project.sh"
          - "open_in_xcode.sh"
          - "DerivedData/**"
          - "Triply.xcodeproj/**"
          - "Triply.xcodeproj"
          - "Triply.xcworkspace/**"
          - "Triply.xcworkspace"
          - "Models/Trip.swift"
          - "Models/Destination.swift"
          - "Managers/TripManager.swift"
    resources:
      - path: Assets.xcassets
      - path: Resources
        buildPhase: none
      - path: Triply.storekit
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.triply.app
      INFOPLIST_FILE: Info.plist
      SWIFT_VERSION: "5.9"
      TARGETED_DEVICE_FAMILY: "1,2" # iPhone and iPad
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      GENERATE_INFOPLIST_FILE: false
      ENABLE_PREVIEWS: true
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: "$(inherited)"
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      DEBUG_INFORMATION_FORMAT: dwarf
    info:
      path: Info.plist
      properties:
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        UIApplicationSupportsIndirectInputEvents: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

